config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root 'main#index'

  get '/users/my_profile', to: 'users#show', as: :user_account_info

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check
  get '/login', to: 'main#login'
  get '/user_management', to: 'main#user_management'
  post '/change_role', to: 'main#change_role'
  get '/about', to: 'main#about'

  get '/', to: 'main#index', as: :main_page
  get '/games/cost', to: 'games#cost', as: 'games_with_cost'
  get '/games/dimensions', to: 'games#dimensions', as: 'games_with_dimensions'
  get '/games/publication_year', to: 'games#publication_year', as: 'games_with_publication_year'

  resources :saved_games, only: %i[index create]

  resources :games do
    collection do
      get 'cost'
      get 'publication_year'
      get 'dimensions'
    end
  end

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/main_controller.rb
# frozen_string_literal: true

class MainController < ApplicationController
  before_action :authenticate_user!, only: %i[user_management change_role]
  before_action :check_admin, only: %i[user_management change_role]

  def index
    @most_watched = Game.where(game_title: ['Lost Recipes', 'Roboco', 'Zero Threat',
                                            'Arté: Hemut', 'Variant: Limits', 'Arté: Mercenas'])
  end

  def user_management
    @users = User.all
  end

  def change_role
    user = User.find(params[:user_id])
    user.update(role: params[:role])
    redirect_to user_management_path, notice: 'User role updated successfully.'
  end

  private

  def check_admin
    return if current_user.admin?

    redirect_to root_path, alert: 'You are not authorized to view this page.'
  end
end

app/helpers/main_helper.rb
# frozen_string_literal: true

module MainHelper
end

app/views/main/about.erb
<!DOCTYPE html>

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title></title>
</head>

<div class="about-container" style="text-align: center;">
  <%= image_tag 'LL_MissionStatement.png', alt: 'Live Lab Mission Statement', style: "display: block; margin: 0 auto;" %>
  <%= image_tag 'LL_About.png', alt: 'Live Lab About Us', style: "display: block; margin: 0 auto;" %>
  <%= link_to "https://www.linkedin.com/company/tamu-live-lab/" do %>
    <%= image_tag 'LL_LinkedIn.png', alt: 'Live Lab LinkedIn', height: 150, width: 150, style: "display: inline-block; margin: 0 auto;" %>
  <% end %>
  <%= link_to "https://www.youtube.com/@livelab7465" do %>
    <%= image_tag 'LL_Youtube.png', alt: 'Live Lab Youtube', height: 150, width: 150, style: "display: inline-block; margin: 0 auto;" %>
  <% end %>
  <%= link_to "https://pvfa.tamu.edu/research/live-lab/" do %>
    <%= image_tag 'LL_Website.png', alt: 'Live Lab Website', height: 150, width: 150, style: "display: inline-block; margin: 0 auto;" %>
  <% end %>
</div>

</div>

app/views/main/index.html.erb
<!DOCTYPE html>
<html lang="en">
<script src="https://cdn.jsdelivr.net/npm/fuse.js@7.0.0"></script>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<div class="body-content">
  <!-- Login-->
  <% if user_signed_in? %>
    <%= link_to "Log Out", destroy_user_session_path, class: "button", 'data-turbo-method': :delete %>
  <% else %>
    <%= link_to "Log In", login_path, class: "button" %>
  <% end %>

  <!--  <p>This is a project of educational video games for LIVE Lab</p>-->

    <%= form_with url: games_path, method: :get, local: true, class:"search-main" do |form| %>
    <div class="search-container">
      <div class="searchbar">
        <%= form.text_field :search, placeholder: "Search..." %>
        <%= form.submit "Search", class: "searchbar-button" %>
      </div>
    </div>
    <% end %>



    <!-- Displaying Images with Links -->
    <div class="container">
      <% @most_watched.each do |game| %>
        <div class="image-container">
          <img src = "<%= game.image %>"  alt="<% game.game_title%>">
          <p><%= link_to game.game_title, game %></p>
        </div>
      <% end %>
  </div>

    <!-- Layouts-->
    <div class="container1">
    <%= link_to "View Games by Cost", cost_games_path, class: "custom-button button-1" %>
    <%= link_to "Latest Game", publication_year_games_path, class: "custom-button button-1" %>
    <%= link_to "3D", dimensions_games_path, class: "custom-button button-1" %>
    </div>



    <!-- Link to User Management Page -->
    <%#= link_to "User Management", user_management_path, class: "button" %>

    <!-- Games-->
    <%#= link_to "View All Games", "/games", class: "button" %>
    <!-- <%= link_to "View All Games", "/games" %>-->
  </div>
</body>
</html>

app/views/main/login.html.erb
<!DOCTYPE html>
<html lang="en">

<% if current_user %>
    <p> You are signed in as <%= current_user.email %> ! </p>
    <p> Your role is <%= current_user.role %> </p>
    <% if current_user.admin? %>
        There are <%= User.count %> users in the system.
    <% end %>

    <%= link_to "Sign out", destroy_user_session_path, 'data-turbo-method': :delete %>
<% else %>
    <p> Please Log in or create an account </p>
    <%= link_to "Sign up", new_user_registration_path %>
    <br />
    <%= link_to "Log in", new_user_session_path %>
<% end %>
</html>

app/views/main/user_management.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Management</title>
    <style>
        table {
            border-collapse: collapse;
            width: 80%;
            margin: 0 auto;
        }
        
        th, td {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }
        
        th {
            background-color: #f2f2f2;
        }
        
        .role-select {
            width: 100%;
        }
        
        .submit-btn {
            margin-top: 10px;
        }
    </style>
</head>

<body>
    <h1>User Management</h1>
    <table>
        <thead>
            <tr>
                <th>Email</th>
                <th>Role</th>
                <th>Change Role</th>
            </tr>
        </thead>
        <tbody>
            <% @users.each do |user| %>
            <tr>
                <td><%= user.email %></td>
                <td><%= user.role %></td>
                <td>
                  <form action="<%= change_role_path %>" method="POST">
                    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
                    <input type="hidden" name="user_id" value="<%= user.id %>">
                    <select name="role" class="role-select">
                      <option value="admin" <%= 'selected' if user.role == 'admin' %>>Admin</option>
                      <option value="moderator" <%= 'selected' if user.role == 'moderator' %>>Moderator</option>
                      <option value="user" <%= 'selected' if user.role == 'user' %>>User</option>
                    </select>
                    <input type="submit" value="Change Role" class="submit-btn">
                  </form>
                </td>
            </tr>
            <% end %>
        </tbody>
    </table>
</body>

</html>