config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root 'main#index'

  get '/users/my_profile', to: 'users#show', as: :user_account_info

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check
  get '/login', to: 'main#login'
  get '/user_management', to: 'main#user_management'
  post '/change_role', to: 'main#change_role'
  get '/about', to: 'main#about'

  get '/', to: 'main#index', as: :main_page
  get '/games/cost', to: 'games#cost', as: 'games_with_cost'
  get '/games/dimensions', to: 'games#dimensions', as: 'games_with_dimensions'
  get '/games/publication_year', to: 'games#publication_year', as: 'games_with_publication_year'

  resources :saved_games, only: %i[index create]

  resources :games do
    collection do
      get 'cost'
      get 'publication_year'
      get 'dimensions'
    end
  end

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/game.rb
# frozen_string_literal: true

class Game < ApplicationRecord
  # Validations
  validates :game_title, presence: true, uniqueness: { case_sensitive: false, message: 'already existed' }
  # validates :url, presence: true,
  #           format: { with: URI::DEFAULT_PARSER.make_regexp(%w[http https]), message: 'must be a valid URL' }

  # Scope for search term matching
  scope :search_by_term, lambda { |search_term|
    where("LOWER(game_title) LIKE :term OR
           LOWER(source) LIKE :term OR
           LOWER(dimensions) LIKE :term OR
           LOWER(publication_year) LIKE :term OR
           LOWER(generalized_subject) LIKE :term OR
           LOWER(subject1) LIKE :term OR
           LOWER(subject2) LIKE :term", term: search_term)
  }

  # Scope for ordering by relevance
  scope :order_relevance, lambda { |search_term|
    select("games.*, CASE
            WHEN LOWER(game_title) LIKE '#{search_term}' THEN 64
            WHEN LOWER(source) LIKE '#{search_term}' THEN 32
            WHEN LOWER(dimensions) LIKE '#{search_term}' THEN 16
            WHEN LOWER(publication_year) LIKE '#{search_term}' THEN 8
            WHEN LOWER(generalized_subject) LIKE '#{search_term}' THEN 4
            WHEN LOWER(subject1) LIKE '#{search_term}' THEN 2
            WHEN LOWER(subject2) LIKE '#{search_term}' THEN 1
            ELSE 0 END AS relevance")
      .order('relevance DESC')
  }
end

app/controllers/games_controller.rb
# frozen_string_literal: true

class GamesController < ApplicationController
  include Filterable
  before_action :set_game, only: %i[show edit update destroy]

  # GET /games or /games.json
  def index
    @games = load_games
    @games = filter_games(@games, params)
    respond_to do |format|
      format.html
      format.js
    end
    @games = @games.paginate(page: params[:page], per_page: 8) unless @games.nil?

    # Remember the sorting option in session or params to persist state after refresh
    @sort_by = params[:sort_by] || 'Relevance'
  end

  # GET /games/1 or /games/1.json
  def show; end

  # GET /games/new
  def new
    unless user_signed_in? && current_user.admin?
      show_forbidden
      return
    end
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
    show_forbidden if !user_signed_in? || current_user.user?
  end

  # POST /games or /games.json
  def create
    unless user_signed_in? && current_user.admin?
      show_forbidden
      return
    end
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to game_url(@game), notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1 or /games/1.json
  def update
    if !user_signed_in? || current_user.user?
      show_forbidden
    else
      update_impl
    end
  end

  # DELETE /games/1 or /games/1.json
  def destroy
    if !user_signed_in? || !current_user.admin?
      show_forbidden
    else
      destroy_impl
    end
  end

  # def current_user
  #   puts "session"
  #   puts session[:email]
  #   @current_user ||= User.find(session[:email])
  # end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_game
    @game = Game.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  GAME_PARAMS = %i[
    game_title url source researcher included exclusion_notes
    publication_year developers publisher used_in_class downloadable
    discontinued generalized_subject subject1 subject2 remainder
    teaching college_users cost game_type genre tags game_time
    dimensions sound platform spanish other_languages notes
  ].freeze

  def game_params
    params.require(:game).permit(GAME_PARAMS)
  end

  def search_games(term)
    search_term = "%#{term.downcase}%"
    Game.search_by_term(search_term)
  end

  def sort_games(games, sort_by, search_term)
    case sort_by
    when 'Title'
      games.order('LOWER(game_title) ASC')
    when 'Publication Year'
      games.order('publication_year DESC')
    when 'Lowest Price'
      games.order('cost_value ASC')
    when 'Highest Price'
      games.order('cost_value DESC')
    when 'Relevance'
      games.order_relevance("%#{search_term.downcase}%")
    else
      games
    end
  end

  def load_games
    @games = Game.all
    @games = search_games(params[:search]) if params[:search].present?
    @games = sort_games(@games, params[:sort_by], params[:search])
  end

  def show_forbidden
    respond_to do |format|
      format.html { render :forbidden, status: :forbidden }
    end
  end

  def update_impl
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to game_url(@game), notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy_impl
    @game.destroy!
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
end

app/helpers/games_helper.rb
# frozen_string_literal: true

module GamesHelper
end

app/views/games/_game_list.html.erb
<% if @games.count.zero? %>
  <p class="no-results-message">No results found.</p>
<% else %>
  <div id="game-list-container">
    <div class="games-container">
      <% @games.each_with_index do |game, index| %>
        <a href="<%= game_path(game) %>" class="game_list_link">
          <div class="image_ctn">
            <% if game.image.present? %>
              <img src="<%= game.image %>" alt="Image 1">
            <% else %>
              <img src="https://static.vecteezy.com/system/resources/previews/005/337/799/original/icon-image-not-found-free-vector.jpg" alt="Default Image">
            <% end %>
          </div>
          <div class="game_info_combined">
            <div class="col game_title_platform">
              <div class="game_title">
                <%= game.game_title %>
              </div>
              <div class="platform">
                <strong>Platform(s):</strong> <%= game.platform %>
              </div>
            </div>
            <div class="publication_year">
              <strong>Publication Year: </strong>
              <%= game.publication_year %>
            </div>
            <div class="cost">
              <strong>Cost: </strong>
              <%= game.cost %>
            </div>
          </div>
        </a>
        <div class="save_button_cnt">
          <%= link_to "Save", saved_games_path(game_id: game.id), data: { turbo_method: :post }, class: "save_button" %>
        </div>
      <% end %>
      <div class="pagination-container">
        <%= will_paginate @games %>
      </div>
    </div>
  </div>
<% end %>

app/views/games/cost.html.erb
<h1>All Games with Cost</h1>
<div class="button-container">
  <%= link_to "Return to main", main_page_path, class: "button" %>
  <div style="margin-right: 30px;"></div> <!-- Adding a margin of 30px between the buttons -->
  <link rel="stylesheet" href="game_index.css">
</div>

<h2>Free Games</h2>
<table id="free-games">
  <thead>
    <tr>
      <th>Title</th>
      <th>Cost</th>
    </tr>
  </thead>
  <tbody>
  <% Game.where("lower(cost) = ? OR cost = ? OR lower(cost) = ? OR cost = ?", "free", "Free. In app purchases", "FREE", "Free ").order(game_title: :asc).each do |game| %>
      <tr>
        <td><%= game.game_title %></td>
        <td><%= game.cost.present? ? game.cost : 'info not included' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h2>Games with Cost Information</h2>
<table id="games-with-cost">
  <thead>
    <tr>
      <th>Title</th>
      <th>Cost</th>
    </tr>
  </thead>
  <tbody>  
  <% Game.where.not("lower(cost) = ? OR cost = ? OR lower(cost) = ? OR cost = ?", "free", "Free. In app purchases", "FREE", "Free ").order(game_title: :asc).each do |game| %>
      <tr>
        <td><%= game.game_title %></td>
        <td><%= game.cost.present? ? game.cost : 'info not included' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h2>Games need for further updates</h2>
<table id="games-needing-updates">
  <thead>
    <tr>
      <th>Title</th>
      <th>Cost</th>
    </tr>
  </thead>
  <tbody>
    <% Game.where(cost: [nil]).order(game_title: :asc).each do |game| %>
      <tr>
        <td><%= game.game_title %></td>
        <td><%= game.cost.present? ? game.cost : 'info not included' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/games/dimensions.html.erb
<h1>All Games with 3D Contents</h1>
<div class="button-container">
  <%= link_to "Return to main", main_page_path, class: "button" %>
  <div style="margin-right: 30px;"></div> <!-- Adding a margin of 30px between the buttons -->
  <link rel="stylesheet" href="game_index.css">
</div>
<table id="3D-games">
  <thead>
    <tr>
      <th>Title</th>
      <th>Dimensions</th>
    </tr>
  </thead>

  <h2>All Games with 3D Contents</h2>
  <tbody>
  <% Game.where(dimensions: ["3D"]).order(dimensions: :desc).each do |game| %>
    <tr>
      <td><%= game.game_title %></td>
      <td><%= game.dimensions.present? ? game.dimensions : 'info not included' %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<table id="2D-games">
<thead>
    <tr>
      <th>Title</th>
      <th>Dimensions</th>
    </tr>
  </thead>
<h2>All Games with 2D Contents</h2>
<tbody>
<% Game.where(dimensions: ["2D"]).order(dimensions: :asc).each do |game| %>
  <tr>
    <td><%= game.game_title %></td>
    <td><%= game.dimensions.present? ? game.dimensions : 'info not included' %></td>
  </tr>
<% end %>
</tbody>
</table>

<table id="other-games">
<thead>
    <tr>
      <th>Title</th>
      <th>Dimensions</th>
    </tr>
  </thead>
<h2>All Games Needed Further Information</h2>
<tbody>
<% Game.where(dimensions: [nil]).order(game_title: :asc).each do |game| %>
  <tr>
    <td><%= game.game_title %></td>
    <td><%= game.dimensions.present? ? game.dimensions : 'info not included' %></td>
  </tr>
<% end %>

<% Game.where.not(dimensions: ["2D", "3D"]).order(dimensions: :asc).each do |game| %>
  <tr>
    <td><%= game.game_title %></td>
    <td><%= game.dimensions.present? ? game.dimensions : 'info not included' %></td>
  </tr>
<% end %>
</tbody>
</table>

app/views/games/edit.html.erb
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="edit_game.css">
</head>

<h2>Editing <%= @game.game_title %></h2>
<br>

<%= render "form", game: @game %>


<div>
  <%= link_to "Show this game", @game %> |
  <%= link_to 'Cancel Edit', games_path, :class => 'btn btn-secondary' %>
</div>

app/views/games/forbidden.erb
<h1>Forbidden</h1>

app/views/games/index.html.erb
<body>
<!--<p style="color: green"><%#= notice %></p>-->

<div class="body-content">
  <h1>Games</h1>

  <%= form_with url: games_path, method: :get, id: 'games_form', local:true do |form| %>
    <div class="search-container">
      <div class="searchbar">
        <%= form.text_field :search, placeholder: "Search...", value: params[:search]%>
        <%= form.submit "Search", class: "searchbar-button" %>
      </div>
      <div class="sortbox">
        <div class="label">Sort by</div>
        <div class="select">
          <%= form.select :sort_by,
                          ['Relevance', 'Title', 'Publication Year', 'Lowest Price', 'Highest Price'],
                          { selected: @sort_by },
                          { onchange: "this.form.submit();", id: "sort-by-dropdown" }%>
        </div>
      </div>
    </div>

  <div class="button-container">
    <%= link_to "Return to main", main_page_path, class: "button" %>
    <div style="margin-right: 30px;"></div> <!-- Adding a margin of 30px between the buttons -->
    <% if user_signed_in? && current_user.admin? %>
      <%= link_to "New Game", new_game_path, class: "button" %>
    <% end %>
  <!--    <link rel="stylesheet" href="game_index.css">-->
    <%= stylesheet_link_tag 'game_index', media: 'all', 'data-turbolinks-track': 'reload' %>
  </div>

    <div class="page_content_cnt">
      <div class="left_page">
        <%= render 'game_list', games: @games %>
      </div>
      <div class="right_page">
        <div class="filter-item">
          <label>Price Range:</label>
          <div class="checkbox_ctn">
            <div class="checkbox_pair">
              <%= form.check_box :price_range_free, { class: 'filter-checkbox', checked: params[:price_range_free]&.include?('true'), onchange: "this.form.submit();"}, 'true', false %>
              <%= label_tag 'price_range_free', 'Free' %>
            </div>
            <div class="checkbox_pair">
              <%= form.check_box :price_range_0to10, { class: 'filter-checkbox', checked: params[:price_range_0to10]&.include?('true'), onchange: "this.form.submit();"}, 'true', false %>
              <%= label_tag 'price_range_0_10', '$0 - $10' %>
            </div>
            <div class="checkbox_pair">
              <%= form.check_box :price_range_10to20, { class: 'filter-checkbox', checked:  params[:price_range_10to20]&.include?('true'), onchange: "this.form.submit();"}, 'true', false %>
              <%= label_tag 'price_range_10_20', '$10 - $20' %>
            </div>
            <div class="checkbox_pair">
              <%= form.check_box :price_range_above20, { class: 'filter-checkbox', checked: params[:price_range_above20]&.include?('true'), onchange: "this.form.submit();" }, 'true', false %>
              <%= label_tag 'price_range_above20', 'Above $20' %>
            </div>
          </div>
        </div>
        <div class="filter-item">
          <label>Platform</label>
          <div class="checkbox_ctn">
            <div class="checkbox_pair">
              <%= form.check_box :platform_windows, { class: 'filter-checkbox', checked: params[:platform_windows]&.include?('true'), onchange: "this.form.submit();" }, 'true', false %>
              <%= label_tag 'platform_windows', 'Windows' %>
            </div>
            <div class="checkbox_pair">
              <%= form.check_box :platform_mac, { class: 'filter-checkbox', checked: params[:platform_mac]&.include?('true'), onchange: "this.form.submit();" }, 'true', false %>
              <%= label_tag 'platform_mac', 'Mac' %>
            </div>
            <div class="checkbox_pair">
              <%= form.check_box :platform_steam, { class: 'filter-checkbox', checked: params[:platform_steam]&.include?('true'), onchange: "this.form.submit();" }, 'true', false %>
              <%= label_tag 'platform_steam', 'Steam' %>
            </div>
            <div class="checkbox_pair">
              <%= form.check_box :platform_web, { class: 'filter-checkbox', checked: params[:platform_web]&.include?('true'), onchange: "this.form.submit();" }, 'true', false %>
              <%= label_tag 'platform_web', 'Web' %>
            </div>
            <div class="checkbox_pair">
              <%= form.check_box :platform_pc, { class: 'filter-checkbox', checked: params[:platform_pc]&.include?('true'), onchange: "this.form.submit();" }, 'true', false %>
              <%= label_tag 'platform_pc', 'PC' %>
            </div>
            <div class="checkbox_pair">
              <%= form.check_box :platform_mobile, { class: 'filter-checkbox', checked: params[:platform_mobile]&.include?('true'), onchange: "this.form.submit();" }, 'true', false %>
              <%= label_tag 'platform_mobile', 'Mobile' %>
            </div>
            <div class="checkbox_pair">
              <%= form.check_box :platform_html5, { class: 'filter-checkbox', checked: params[:platform_html5]&.include?('true'), onchange: "this.form.submit();" }, 'true', false %>
              <%= label_tag 'platform_html5', 'HTML5' %>
            </div>
            <div class="checkbox_pair">
              <%= form.check_box :platform_vr, { class: 'filter-checkbox', checked: params[:platform_vr]&.include?('true'), onchange: "this.form.submit();" }, 'true', false %>
              <%= label_tag 'platform_vr', 'VR' %>
            </div>
          </div>
        </div>
        <div class="filter-item">
          <label>Number of Players</label>
          <div class="checkbox_ctn">
            <div class="checkbox_pair">
              <%= form.check_box :genre_single, { class: 'filter-checkbox', checked:  params[:genre_single]&.include?('true'), onchange: "this.form.submit();"}, 'true', false %>
              <%= label_tag 'genre_single', 'Single-player' %>
            </div>
            <div class="checkbox_pair">
              <%= form.check_box :genre_multi, { class: 'filter-checkbox', checked:  params[:genre_multi]&.include?('true'), onchange: "this.form.submit();"}, 'true', false %>
              <%= label_tag 'genre_multi', 'Multi-player' %>
            </div>
          </div>
        </div>
        <div class="filter-item">
          <label>Subject</label>  <!-- art, biology, ecology, medical, math, nursing, language, geography -->
          <div class="checkbox_ctn">
            <div class="checkbox_pair">
              <%= form.check_box :subject_art, { class: 'filter-checkbox', checked: params[:subject_art]&.include?('true'), onchange: "this.form.submit();" }, 'true', false %>
              <%= label_tag 'subject_art', 'Art' %>
            </div>
            <div class="checkbox_pair">
              <%= form.check_box :subject_biology, { class: 'filter-checkbox', checked: params[:subject_biology]&.include?('true'), onchange: "this.form.submit();" }, 'true', false %>
              <%= label_tag 'subject_biology', 'Biology' %>
            </div>
            <div class="checkbox_pair">
              <%= form.check_box :subject_ecology, { class: 'filter-checkbox', checked: params[:subject_ecology]&.include?('true'), onchange: "this.form.submit();" }, 'true', false %>
              <%= label_tag 'subject_ecology', 'Ecology' %>
            </div>
            <div class="checkbox_pair">
              <%= form.check_box :subject_medical, { class: 'filter-checkbox', checked: params[:subject_medical]&.include?('true'), onchange: "this.form.submit();" }, 'true', false %>
              <%= label_tag 'subject_medical', 'Medical' %>
            </div>
            <div class="checkbox_pair">
              <%= form.check_box :subject_nursing, { class: 'filter-checkbox', checked: params[:subject_nursing]&.include?('true'), onchange: "this.form.submit();" }, 'true', false %>
              <%= label_tag 'subject_nursing', 'Nursing' %>
            </div>
            <div class="checkbox_pair">
              <%= form.check_box :subject_math, { class: 'filter-checkbox', checked: params[:subject_math]&.include?('true'), onchange: "this.form.submit();" }, 'true', false %>
              <%= label_tag 'subject_math', 'Math' %>
            </div>
            <div class="checkbox_pair">
              <%= form.check_box :subject_language, { class: 'filter-checkbox', checked: params[:subject_language]&.include?('true'), onchange: "this.form.submit();" }, 'true', false %>
              <%= label_tag 'subject_language', 'Language' %>
            </div>
            <div class="checkbox_pair">
              <%= form.check_box :subject_geography, { class: 'filter-checkbox', checked: params[:subject_geography]&.include?('true'), onchange: "this.form.submit();" }, 'true', false %>
              <%= label_tag 'subject_geography', 'Geography' %>
            </div>
          </div>
        </div>
        <div class="filter-item">
          <label>2D/3D</label>
          <div class="checkbox_ctn">
            <div class="checkbox_pair">
              <%= form.check_box :dimensions_2D, { class: 'filter-checkbox', checked: params[:dimensions_2D]&.include?('true'), onchange: "this.form.submit();" }, 'true', false %>
              <%= label_tag 'dimensions_2D', '2D' %>
            </div>
            <div class="checkbox_pair">
              <%= form.check_box :dimensions_3D, { class: 'filter-checkbox', checked: params[:dimensions_3D]&.include?('true'), onchange: "this.form.submit();" }, 'true', false %>
              <%= label_tag 'dimensions_3D', '3D' %>
            </div>
          </div>
        </div>
        <div class="filter-item">
          <label>Other Features</label>
          <div class="checkbox_ctn">
            <div class="checkbox_pair">
              <%= form.check_box :other_features_uic, { class: 'filter-checkbox', checked: params[:other_features_uic]&.include?('true'), onchange: "this.form.submit();" }, 'true', false %>
              <%= label_tag 'other_features_uic', 'Used in Classroom' %>
            </div>
            <div class="checkbox_pair">
              <%= form.check_box :other_features_downloadable, { class: 'filter-checkbox', checked: params[:other_features_downloadable]&.include?('true'), onchange: "this.form.submit();" }, 'true', false %>
              <%= label_tag 'other_features_downloadable', 'Downloadable' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>
</body>

app/views/games/index.js.erb
document.getElementById('game-list-container').innerHTML = '<%= j render "game_list", games: @games %>';

app/views/games/new.html.erb
<h2>Creating New Game</h2>

<%= render "form", game: @game %>

<br>

<div>
  <%= link_to "Back to games", games_path %>
</div>

app/views/games/publication_year.html.erb
<h1>All Games with Publication Year</h1>
<div class="button-container">
  <%= link_to "Return to main", main_page_path, class: "button" %>
  <div style="margin-right: 30px;"></div> <!-- Adding a margin of 30px between the buttons -->
  <link rel="stylesheet" href="game_index.css">
</div>
<table id="latest-games">
  <thead>
    <tr>
      <th>Title</th>
      <th>Latest Game</th>
    </tr>
  </thead>
  <h2>  Latest Games </h2>
  <tbody>
  <% games_with_numeric_years = Game.where("publication_year LIKE ?", "____").order(publication_year: :desc) %>
  <% games_with_numeric_years.each do |game| %>
    <tr>
      <td><%= game.game_title %></td>
      <td><%= game.publication_year %></td>
    </tr>
  <% end %>
</table>

<table id="games-tobechecked">
<h2>  Publication Year - Needed to be Checked </h2>
<tbody>
<% games_with_numeric_content = Game.where.not(publication_year: nil).select { |game| game.publication_year.to_s.match?(/\d/) && game.publication_year.to_s.length != 4 } %>
<% games_with_numeric_content.each do |game| %>
    <tr>
    <td><%= game.game_title %></td>
    <td><%= game.publication_year %></td>
  </tr>
<% end %>
</tbody>
</table>


<table id="games-with-updates">
<h2>Games need for further updates</h2>
  <tbody>
  <% Game.where(publication_year: [nil, "UC"]).order(game_title: :asc, publication_year: :asc).each do |game| %>
    <tr>
      <td><%= game.game_title %></td>
      <td><%= game.publication_year.present? ? game.publication_year : 'info not included' %></td> 
    </tr>
  <% end %>  
  </tbody>
</table>

app/views/games/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Game Information</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<body>

<p style="color: green"><%= notice %></p>

<h1 style="text-align: center"><%= @game.game_title %></h1>
<% if @game.image %>
  <img src="<%= @game.image %>" alt="Game Image" style="max-width: 1200px; display: block; margin: 0 auto;">
<% end %>

<div class="games-container">
  <%= link_to "Visit this Game", @game.url, class:  "custom-button button-1" %>
  <%= button_to "Save", saved_games_path(game_id: @game.id), method: :post, class: "custom-button button-2", id: "save_button_#{@game.id}" %>
</div>

<div class="games-container">
  <table>
    <% ignored_attributes = ["id", "researcher", "included", "exclusion_notes"] %>

    <% @game.attributes.each do |attribute, value| %>
      <tr>
        <% if ignored_attributes.exclude?(attribute) %>
          <th><%= attribute.titleize %></th>
          <% if attribute == "image" %>
            <td><a href="<%= value %>"><img src="<%= value %>" alt="Game Image" style="max-width: 1000px" ></a></td>
          <% else %>
            <td><%= value %></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </table>
</div>

<div class="container1">
  <% if user_signed_in? %>
    <% if current_user.admin? || current_user.moderator? %>
      <%= link_to "Edit this game", edit_game_path(@game), class:  "custom-button button-1" %>
    <% end %>
  <% end %>

  <% if user_signed_in? %>
    <% if current_user.admin? %>
    <%= button_to "Destroy this game", @game, method: :delete, class:  "custom-button btn-danger",
                  data: { turbo_confirm: "Are you sure to delete?", disable_with: "Processing..."} %>
    <% end %>
  <% end %>

  <%= link_to "Back to games", games_path , class:  "custom-button button-1" %>
</div>

</body>
</html>